Backport support for nested maps and tuples
eosnetworkfoundation/mandel.cdt pull request #44
Opened 2022-07-28 15:41 UTC by ndcgundlach

Backport support for nested maps and tuples
## Change Description

This PR adds support for nested maps and tuples in Mandel contracts.

## API Changes
- [ ] API Changes

## Documentation Additions
- [ ] Documentation Additions

2022-07-29 15:03 UTC, ClaytonCalabrese commented
Seems like toolchain_tests are failing as of this PR

2022-07-29 15:03 UTC, ClaytonCalabrese requested changes

2022-07-29 15:03 UTC, ClaytonCalabrese commented on tools/include/eosio/abigen.hpp
> +
Is this KV part that needs to be removed?

2022-07-29 15:12 UTC, ndcgundlach commented
> Seems like toolchain_tests are failing as of this PR

I pushed up a fix for that.  You may want to retry.

2022-07-29 16:02 UTC, ClaytonCalabrese commented
> > Seems like toolchain_tests are failing as of this PR
> 
> I pushed up a fix for that. You may want to retry.

You're right, my code was out of date, and it passes now.

2022-08-01 14:09 UTC, ClaytonCalabrese approved these changes

2022-08-01 14:49 UTC, merged